- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable the nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: run app-pre-requisites
  ansible.builtin.import_role:
    name: common
    task_path: app-pre-req # .yaml is not mandatory

# if there is change in configuration only, then you need to restart the nginx
- name: copy the backend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx

# - name:  Restart the nginx
#   ansible.builtin.service:
#     name: nginx 
#     state: restarted
