- name: Installing MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: latest # or latest
  
- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - pyMySQL
    - cryptography # for use passwords
    executable: pip3.9 # pip3.11, if python version is 3.11


- name: start and enable the mysql-server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes


# check password is already setup or not
- name: check DB Connection
  community.mysql.mysql_info:
    login_user: "{{ login_user }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: print output
  ansible.builtin.debug:
    msg: "output: {{ mysql_connection_output }}"

- name: MySQL password setup
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connection_output.failed is true # dont give {{ }} in when condition